Oel8 template
vmware-samples/packer-examples-for-vsphere pull request #670
Opened 2023-09-17 10:45 UTC by virtualistic

# 

## Summary of Pull Request

## Type of Pull Request

- [ ] This is a bugfix. `type/bug`
- [ X] This is an enhancement or feature. `type/feature` or `type/enhancement`
- [ ] This is a documentation update. `type/docs`
- [ ] This is a refactoring update. `type/refactor`
- [ ] This is a chore. `type/chore`
- [ ] This is something else.
      Please describe:

## Related to Existing Issues

Issue Number: N/A

## Test and Documentation Coverage

- [X ] Tests have been completed.
- [ ] Documentation has been added or updated.

## Breaking Changes?

- [ ] Yes, there are breaking changes.
- [ X] No, there are no breaking changes.

2023-09-17 14:21 UTC, tenthirtyam reviewed
The build.yaml needs to be updated. This is used to generated the build.sh with gomplate.

The README.md would also need an update.

2023-09-17 14:26 UTC, tenthirtyam commented
Marked as drafted until the CLA is approved.

2023-09-17 15:54 UTC, virtualistic commented
I added a new commit which added Oracle Linux as an entry to the README
Also added an entry for build.yaml

2023-09-17 17:32 UTC, tenthirtyam requested changes
Hi @virtualistic -

Please run the following to generate the `build.sh`:

```bash
gomplate -c build.yaml -f build.tmpl -o build.sh
```

Additionally, in the `README.md` and update is needed to list the download information for each the distribution:

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.

2023-09-17 18:59 UTC, virtualistic commented
Created a new commit that:
- Rebuilt the build.sh using the command:
`gomplate -c build.yaml -f build.tmpl -o build.sh`

- Added the source for the Oracle ISO to the README

2023-09-17 19:25 UTC, tenthirtyam commented
Thanks! Once the CLA is approved I'll run the standard tests. I have a couple updates and pull requests that I have in my backlog for this side project but will prioritize as soon as possible.

Might I ask you to open an enhancement issue and link the pull request with "Closes #x" when time permits.

2023-09-17 19:38 UTC, virtualistic commented
> Thanks! Once the CLA is approved I'll run the standard tests. I have a couple updates and pull requests that I have in my backlog for this side project but will prioritize as soon as possible.
> 
> Might I ask you to open an enhancement issue and link the pull request with "Closes #x" when time permits.

Sure, no problem.   ( Enhancement request has a typo btw: "Please add a short _decsription_." )
When  I open a new Enhancement Request, there are several **mandatory** fields:
Description
Use Case(s)
Potential Configuration
Do I type:  "closes  # 670" in each field or do you want that placed in a certain field?

2023-09-17 20:06 UTC, tenthirtyam commented
Closes is put here in the PR back to the enhancement issue.

thanks for the note on the issue form! :)

2023-09-17 20:30 UTC, virtualistic commented
closes #671

2023-09-17 20:50 UTC, virtualistic commented
> Closes is put here in the PR back to the enhancement issue.
> 
> thanks for the note on the issue form! :)

Most welcome!
Please note that the Oracle iso has an annoying mix of CaPs in its filename which I changed to all lowercase after I download the iso and also used the lowercase name in the packer file that references the iso.
So 2 questions:
1) Do you want me to use the original filename of the ISO in this pull request?

2) I also changed the iso_path to `iso/misc` for my situation in the `linux-oel.auto.pkrvars.hcl` . Do you want me to change it to `iso/linux/oracle` for this pull request?

2023-09-17 20:54 UTC, tenthirtyam commented
Please use the original file name from the vendor and an oel or oracle path.

2023-09-18 19:19 UTC, virtualistic commented
Added a new commit with the iso_path in line with the rest of the project and replaced the iso name with that of the vendor.

2023-09-20 12:13 UTC, tenthirtyam commented
Would you consider including OEL9, too?

2023-09-20 22:15 UTC, tenthirtyam commented on README.md
> +     - [Download][download-linux-oel-8] the latest release of the **FULL** `.iso` image. (_e.g.,_ `oraclelinux-r8-u8-x86_64-dvd.iso`)
```suggestion
     - [Download][download-linux-oel-8] the latest release of the **FULL** `.iso` image. (_e.g.,_ `OracleLinux-R8-U8-x86_64-dvd.iso`)
```

2023-09-20 22:17 UTC, tenthirtyam commented on builds/linux/oracle/8/variables.pkr.hcl
> +  description = "The guest operating system name. Used for naming . (e.g. 'rhel')"
```suggestion
  description = "The guest operating system name. Used for naming . (e.g. 'oel')"
```

2023-09-20 22:18 UTC, tenthirtyam commented on builds/linux/oracle/8/variables.pkr.hcl
> +  description = "The guest operating system type, also know as guestid. (e.g. 'rhel8_64Guest')"
```suggestion
  description = "The guest operating system type, also know as guestid. (e.g. 'oracleLinux8_64Guest')"
```

2023-09-20 22:18 UTC, tenthirtyam commented on builds/linux/oracle/8/variables.pkr.hcl
> +  description = "The path on the source vSphere datastore for ISO image. (e.g. 'iso/linux/rhel')"
```suggestion
  description = "The path on the source vSphere datastore for ISO image. (e.g. 'iso/linux/oel')"
```

2023-09-20 22:21 UTC, tenthirtyam commented on builds/linux/oracle/8/variables.pkr.hcl
> +  description = "The file name of the ISO image used by the vendor. (e.g. 'rhel-<verssion>-x86_64-dvd.iso')"
```suggestion
  description = "The file name of the ISO image used by the vendor. (e.g. 'OracleLinux-<version>-x86_64-dvd.iso')"
```

2023-09-20 22:28 UTC, tenthirtyam requested changes
Minor changes.

Would you consider adding OEL 9?

2023-09-21 21:06 UTC, virtualistic commented
Don't know if v9 will work because the latest vCenter v7 does **not**  offer Oracle Linux 9 as a guest os . 
(while my local ESXi server does)
![2023-09-21 21_29_16-vCenter-oracleinux-versions](https://github.com/vmware-samples/packer-examples-for-vsphere/assets/19362526/d1420389-0694-4d22-a26c-2ed8a5963564)

2023-09-21 21:13 UTC, virtualistic commented
I agree with your suggested changes. Think it's best I edit my repo and create a new commit with the changes? 
Or should I do a "signoff and commit suggestion" from the GitHub UI?

2023-09-21 21:20 UTC, tenthirtyam commented
> I agree with your suggested changes. Think it's best I edit my repo and create a new commit with the changes?
> Or should I do a "signoff and commit suggestion" from the GitHub UI?

 "signoff and commit suggestion" is fine, but I generally just amend the last commit and force push.

2023-09-21 21:23 UTC, tenthirtyam commented
> Don't know if v9 will work because the latest vCenter v7 does **not** offer Oracle Linux 9 as a guest os . (while my local v7 ESXi server does).

Use `other5xLinux64Guest`. 😃

2023-09-22 10:29 UTC, virtualistic commented
Ok, I changed all the requested files and did a :
```
git add -A
git commit --amend --no-edit
git push -f
```
Will have look if it's easy to add Oracle 9 now using my own Oracle 8 files :)

2023-09-22 13:47 UTC, virtualistic commented
Ok, pushed a new commit with an Oracle 9 Template.
![2023-09-22 13_56_08-oel9](https://github.com/vmware-samples/packer-examples-for-vsphere/assets/19362526/5f885f5b-3dab-48b3-8746-1917eaece6f4)

2023-09-22 13:49 UTC, tenthirtyam commented
Awesome! thank you!!

2023-09-22 13:51 UTC, tenthirtyam approved these changes
LGTM!

2023-09-22 16:34 UTC, tenthirtyam approved these changes
LGTM!

2023-09-22 16:37 UTC, merged