chore: updated debian 12 and ubuntu 22.04 links
vmware-samples/packer-examples-for-vsphere pull request #984
Opened 2024-11-29 13:45 UTC by Benedikt-Frenzel

## Summary of Pull Request

Updated the download links for Debian 12 and Ubuntu 22.04

## Type of Pull Request

- [ ] This is a bugfix. `type/bug`
- [ ] This is an enhancement or feature. `type/feature` or `type/enhancement`
- [ ] This is a documentation update. `type/docs`
- [ ] This is a refactoring update. `type/refactor`
- [x] This is a chore. `type/chore`
- [ ] This is something else.
      Please describe:

## Related to Existing Issues

Issue Number: N/A

## Test and Documentation Coverage

- [x] Tests have been completed.
- [ ] Documentation has been added or updated.

## Breaking Changes?

- [ ] Yes, there are breaking changes.
- [x] No, there are no breaking changes.

2024-11-29 15:03 UTC, tenthirtyam requested changes

2024-11-29 15:03 UTC, tenthirtyam commented on project.json
> +                                        "download_link": "https://mirror.cogentco.com/debian-cd/12.8.0/amd64/iso-cd/debian-12.7.0-amd64-netinst.iso",
Doesn't seem correct.

2024-11-29 15:06 UTC, tenthirtyam commented
Commits require the sign off.

2024-12-01 21:10 UTC, Benedikt-Frenzel commented
I double checked and bumped all the URLs for:

- AlmaLinux
- Debian
- Fedora Server
- Rocky
- Ubuntu

2024-12-01 23:48 UTC, tenthirtyam commented
Your commit still requires a sign-off.

2024-12-01 23:53 UTC, tenthirtyam requested changes
Each commit requires a sign-off.

For example, squash or amend each and included your version of the below based on your GitHub display name and the associated email address in your GitHub account.

```
Signed-off-by: Ryan Johnson <ryan.johnson@broadcom.com>
```

2024-12-01 23:53 UTC, tenthirtyam commented on .gitignore
> +## Ignore ISO path
```suggestion
## Ignore ISO Path
```

2024-12-01 23:53 UTC, tenthirtyam commented on .gitignore
> +
```suggestion
```

2024-12-01 23:53 UTC, tenthirtyam commented on project.json
> +                                        "checksum": "https://dl.rockylinux.org/vault/rocky/9.5/isos/x86_64/CHECKSUM"
Not mentioned in the summary.

2024-12-01 23:53 UTC, tenthirtyam commented on project.json
> +                                        "checksum": "https://repo.almalinux.org/almalinux/9.5/isos/x86_64/CHECKSUM"
Not mentioned in the summary.

2024-12-01 23:53 UTC, tenthirtyam commented on project.json
> +                                "version": "41",
This would need to be updated in the docs and `README.md`.

2024-12-02 00:00 UTC, tenthirtyam requested changes
If v9 for both Rocky Linux and AlmaLinux are updated, then the same should be done for RHEL.

2024-12-02 15:49 UTC, Benedikt-Frenzel commented
Updated the Readme and signed the commit. 
I cannot check and fix RHEL as I don't have a subscription, but I updated OL aswell.

2024-12-02 16:07 UTC, tenthirtyam commented on README.md
> +| Fedora Server                | 41        |
Also here: https://github.com/vmware-samples/packer-examples-for-vsphere/blob/fb37d5e8488c5f253461c8328e7cad32202d76a5/docs/index.md?plain=1#L37

2024-12-02 16:08 UTC, tenthirtyam commented on project.json
> +                                "version": "41",
https://github.com/vmware-samples/packer-examples-for-vsphere/blob/fb37d5e8488c5f253461c8328e7cad32202d76a5/docs/index.md?plain=1#L37

2024-12-02 16:16 UTC, tenthirtyam commented
@Benedikt-Frenzel Please pull the latest. I've squashed and updated the commits.

2024-12-02 16:20 UTC, tenthirtyam commented on project.json
> +                                "version": "41",
Resolved in https://github.com/vmware-samples/packer-examples-for-vsphere/commit/3cb90f4e13531fc53075a486a3852e6b6cdd4444.

2024-12-02 16:30 UTC, tenthirtyam requested changes
If v9 for Rocky Linux, AlmaLinux, and Oracle Linux are updated, then the same should be done for RHEL 9 but updating the checksum to the v9.5 release.

2024-12-02 16:41 UTC, Benedikt-Frenzel commented
I just saw that I also should update the paths in the .hcl.example files, will do that later.

2024-12-02 16:43 UTC, tenthirtyam commented
> `b3005f2`

Resol

> If v9 for Rocky Linux, AlmaLinux, and Oracle Linux are updated, then the same should be done for RHEL 9 but updating the checksum to the v9.5 release.

Resolved in b3005f2.

2024-12-02 16:59 UTC, tenthirtyam commented
> I just saw that I also should update the paths in the .hcl.example files, will do that later.

Addressed in https://github.com/vmware-samples/packer-examples-for-vsphere/commit/691784217ec93e6d144869929514eb4dd69b93bd. Also needed an update to the path for fedora and the gitlab ci yaml.

2024-12-02 19:08 UTC, tenthirtyam commented
Please pull the latest. I've squashed and updated the commits.

2024-12-02 19:14 UTC, tenthirtyam approved these changes
LGTM

2024-12-02 19:15 UTC, merged