feat: added Centos 10 stream
vmware-samples/packer-examples-for-vsphere pull request #989
Opened 2024-12-04 17:09 UTC by burnsjared0415

# 

## Summary of Pull Request
added Centos 10 Stream to Project

## Type of Pull Request

- [ ] This is a bugfix. `type/bug`
- [x] This is an enhancement or feature. `type/feature` or `type/enhancement`
- [ ] This is a documentation update. `type/docs`
- [ ] This is a refactoring update. `type/refactor`
- [ ] This is a chore. `type/chore`
- [ ] This is something else.
      Please describe:

## Related to Existing Issues

Issue Number: N/A

## Test and Documentation Coverage

- [ ] Tests have been completed.
- [x] Documentation has been added or updated.

## Breaking Changes?

- [ ] Yes, there are breaking changes.
- [x] No, there are no breaking changes.

2024-12-04 17:26 UTC, tenthirtyam requested changes
The README.md will need an update as will the GitLab CI files.

2024-12-04 17:26 UTC, tenthirtyam commented on docs/getting-started/downloads.md
> +|                                                             | 10 Stream | :octicons-check-circle-16:{ .green }                                  |
Can you put 10 before 9?

2024-12-04 17:26 UTC, tenthirtyam commented on docs/index.md
> +|                                                            | 10 Stream | :octicons-check-circle-16:{.green} | :octicons-check-circle-16:{.green} | :octicons-check-circle-16:{.green} | :octicons-che
Can you put 10 before 9?

2024-12-04 17:27 UTC, burnsjared0415 commented on docs/getting-started/downloads.md
> +|                                                             | 10 Stream | :octicons-check-circle-16:{ .green }                                  |
done

2024-12-04 17:28 UTC, burnsjared0415 commented on docs/index.md
> +|                                                            | 10 Stream | :octicons-check-circle-16:{.green} | :octicons-check-circle-16:{.green} | :octicons-check-circle-16:{.green} | :octicons-che
done

2024-12-04 18:01 UTC, tenthirtyam commented on CHANGELOG.md
> +- Added Centos 10 stream to project.
```suggestion
- Adds Centos 10 stream to project.
```

2024-12-04 18:02 UTC, tenthirtyam commented on docs/index.md
> +|                                                            | 9 Stream | :octicons-check-circle-16:{.green} | :octicons-check-circle-16:{.green} | :octicons-check-circle-16:{.green} | :octicons-chec
```suggestion
| :fontawesome-brands-centos: CentOS @span                   | 10 Stream | :octicons-check-circle-16:{.green} | :octicons-check-circle-16:{.green} | :octicons-check-circle-16:{.green} | :octicons-check-circle-16:{.green} |
|                                                            | 9 Stream  | :octicons-check-circle-16:{.green} | :octicons-check-circle-16:{.green} | :octicons-check-circle-16:{.green} | :octicons-check-circle-16:{.green} |
```

2024-12-04 18:02 UTC, tenthirtyam commented on docs/index.md
> +|                                                            | 9 Stream | :octicons-check-circle-16:{.green} | :octicons-check-circle-16:{.green} | :octicons-check-circle-16:{.green} | :octicons-chec
Alignment.

2024-12-04 18:04 UTC, tenthirtyam requested changes
Update here: https://github.com/burnsjared0415/packer-examples-for-vsphere/blob/17a9469485a6dd9339734c401acdfec9e9b9df8a/README.md?plain=1#L42

2024-12-04 18:06 UTC, tenthirtyam requested changes
And upate here, plus remove CentOS 7: https://github.com/vmware-samples/packer-examples-for-vsphere/blob/4880b2c8d55499e00592499172f09aaf0d555c6e/build-ci.yaml#L109-L120

Then run gomplate to generate a new gitlab yml.

2024-12-05 15:00 UTC, tenthirtyam commented
Resolved the needed changes in fa01fef.

2024-12-05 15:09 UTC, tenthirtyam approved these changes
LGTM!

2024-12-05 15:10 UTC, merged